### ISSUE TITLE
`fzero` returns a large root that is not a root

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaMath/Roots.jl#182]
```julia
using Roots

f(x) = 4 / (x + 1)
ω_c = fzero(ω -> angle(f(im * ω)) + π, 0.001) # extremely large

angle(f(im * ω_c)) + π # not zero
```

**Comment by jverzani** [comment]
Yeah, this is an issue with *relative* tolerances: they don't work well for numbers near 0 and they don't work well for really large  numbers, yet they work   better than absolute tolerances by default.

For this problem we have:

```
F(ω) = angle(f(im * ω)) + π
x = fzero(F, 0.001)
F(x) <=  x*eps() # true
```

You  would want to   try something like:
```
x = fzero(F, 0.001, rtol=0,  atol=sqrt(eps()))
```
Which  gives an errror instead of an answer, as the algorithm escapes towards `oo`.

**Comment by SimonEnsemble** [comment]
@jverzani thank you for explaining!

interesting that relative tolerance is defined in terms of the output / input, given that the inputs and outputs could have very different scales and units.

though, how "relatively far" `F(x)` is from zero, however, would make no sense!
