### ISSUE TITLE
Bug with some trivial functions

### ISSUE THREAD

**Issue by Codsilla** [JuliaMath/Roots.jl#339]
The following `find_zeros(x-> 0,-2,2)` crashes and gives the following error: `ArgumentError: start and stop must be finite, got NaN and NaN`.

**Comment by longemen3000** [comment]
this should error higher in the stack. the error occurs because https://github.com/JuliaMath/Roots.jl/blob/d2182bcd4e7f29967ea72c988cea93514cdcc8c2/src/find_zeros.jl#L76 returns `NaN` for this function and arguments (correct behaviour). then, those NaNs get passed to _fz: https://github.com/JuliaMath/Roots.jl/blob/d2182bcd4e7f29967ea72c988cea93514cdcc8c2/src/find_zeros.jl#L325-L328. the error occurs because `a0 == NaN`  and `b0 == NaN`, and `_fz` tries to create a range with `start = a0` and `stop = b0`.

**Comment by jverzani** [comment]
Thanks, I'll have a look at fixing this when I get a chance.

**Comment by jverzani** [comment]
Closed by #340
